# Generated by Django 2.0 on 2017-12-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topologies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dport1', models.CharField(max_length=200)),
                ('dport2', models.CharField(max_length=200)),
                ('delay', models.FloatField(max_length=200)),
                ('judge', models.CharField(max_length=200)),
                ('updated', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vlans',
            fields=[
                ('vlanid', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.CharField(max_length=200)),
                ('end', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
        ),
    ]
