# Generated by Django 2.0 on 2017-12-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topologies',
            name='delay',
            field=models.FloatField(max_length=512),
        ),
    ]
