# Generated by Django 2.0 on 2017-12-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_auto_20171220_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topologies',
            name='delay',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vlans',
            name='created_at',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vlans',
            name='end',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vlans',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vlans',
            name='start',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vlans',
            name='updated_at',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
