# Generated by Django 2.0 on 2017-12-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_auto_20171220_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topologies',
            name='delay',
            field=models.FloatField(default=1, max_length=200),
        ),
    ]
