# Generated by Django 2.0 on 2017-12-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_auto_20171220_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.CharField(max_length=200, null=True)),
                ('end', models.CharField(max_length=200, null=True)),
                ('route', models.TextField(null=True)),
            ],
        ),
    ]
