# Generated by Django 2.0 on 2018-01-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0006_route_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datapath', models.TextField(null=True)),
                ('object_datapath', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vlans',
            name='path_length',
            field=models.IntegerField(null=True),
        ),
    ]
