# Generated by Django 2.0 on 2018-01-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0008_auto_20180125_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_name', models.TextField(null=True)),
                ('ip_addres', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='datapath',
            old_name='host_name',
            new_name='datapath',
        ),
        migrations.RenameField(
            model_name='datapath',
            old_name='ip_addres',
            new_name='object_datapath',
        ),
    ]
