# Generated by Django 2.0 on 2018-01-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0009_auto_20180125_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosts',
            old_name='ip_addres',
            new_name='ip_address',
        ),
    ]
