# Generated by Django 2.0 on 2018-02-14 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0010_auto_20180125_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datapath',
        ),
    ]
