# Generated by Django 2.0 on 2018-02-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0014_datapath'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datapath',
        ),
    ]
