# Generated by Django 2.0 on 2018-02-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0017_delete_datapath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datapath', models.TextField(null=True)),
                ('object_datapath', models.TextField(null=True)),
            ],
        ),
    ]
